image: Visual Studio 2017
version: 1.0.{build}
build_script:
- ps: >-
    dotnet build Quartz.Extensions.Microsoft.DependencyInjection/Quartz.Extensions.Microsoft.DependencyInjection.csproj
after_test:
- ps: >-
    dotnet pack Quartz.Extensions.Microsoft.DependencyInjection/Quartz.Extensions.Microsoft.DependencyInjection.csproj -c Release --include-symbols
artifacts:
- path: Quartz.Extensions.Microsoft.DependencyInjection/bin/Release/*.nupkg
  name: Quartz.Extensions.Microsoft.DependencyInjection
deploy:
- provider: NuGet
  api_key:
    secure: R8G4Xks6wlJ6LCQ9Msj51rWrH3/Tn1dfdbm1FR22kUBTPsSSQaybSEZCf7PMDJU/
  skip_symbols: true